// <auto-generated />
namespace EFController.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class banco02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(banco02));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231902576_banco02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
